In [1]:
# For numpy

In [2]:
import numpy as np


In [4]:
x=0

# Num Mat

In [7]:
x=np.array([[1,2],[4,5]])
y=np.array([[6,7],[8,9]])
print(x)
print(y)

[[1 2]
 [4 5]]
[[6 7]
 [8 9]]


In [8]:
print(x*y)

[[ 6 14]
 [32 45]]


In [9]:
x+y

array([[ 7,  9],
       [12, 14]])

In [10]:
x/y

array([[0.16666667, 0.28571429],
       [0.5       , 0.55555556]])

In [11]:
z=x*y
print(z)

[[ 6 14]
 [32 45]]


In [12]:
np.dot(x,y)

array([[22, 25],
       [64, 73]])

In [13]:
np.cross(x,y)

array([-5, -4])

In [15]:
a=np.array([[1,2],[2,1]])
b=np.array([[3,3],[2,2]])


In [17]:
print(np.cross(a,b))
print(np.dot(a,b))

[-3  2]
[[7 7]
 [8 8]]


In [18]:
c=np.random.randint(0,100,(5,7))
print(c)

[[85 83 43 18 77 10  6]
 [ 9 24 85  0  9 32 48]
 [48 71 52  0 21 76 38]
 [52  4 13 90 58 64 74]
 [70 53 25 78 15 65 91]]


In [19]:
print(c.sum())

1587


In [21]:
print(c.sum(axis=0))  # 0 across column 
print(c.sum(axis=1))  # 1 across rows

[264 235 218 186 180 247 257]
[322 207 306 355 397]


In [22]:
print(c.mean())

45.34285714285714


In [23]:
print(c.mean(axis=0))
print(c.mean(axis=1))

[52.8 47.  43.6 37.2 36.  49.4 51.4]
[46.         29.57142857 43.71428571 50.71428571 56.71428571]


In [24]:
np.sin(c)

array([[-0.17607562,  0.96836446, -0.83177474, -0.75098725,  0.99952016,
        -0.54402111, -0.2794155 ],
       [ 0.41211849, -0.90557836, -0.17607562,  0.        ,  0.41211849,
         0.55142668, -0.76825466],
       [-0.76825466,  0.95105465,  0.98662759,  0.        ,  0.83665564,
         0.56610764,  0.29636858],
       [ 0.98662759, -0.7568025 ,  0.42016704,  0.89399666,  0.99287265,
         0.92002604, -0.98514626],
       [ 0.77389068,  0.39592515, -0.13235175,  0.51397846,  0.65028784,
         0.82682868,  0.10598751]])

In [25]:
np.log10(c)

C:\Users\KumarCha05\AppData\Local\Temp\ipykernel_176680\2814158553.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(c)


array([[1.92941893, 1.91907809, 1.63346846, 1.25527251, 1.88649073,
        1.        , 0.77815125],
       [0.95424251, 1.38021124, 1.92941893,       -inf, 0.95424251,
        1.50514998, 1.68124124],
       [1.68124124, 1.85125835, 1.71600334,       -inf, 1.32221929,
        1.88081359, 1.5797836 ],
       [1.71600334, 0.60205999, 1.11394335, 1.95424251, 1.76342799,
        1.80617997, 1.86923172],
       [1.84509804, 1.72427587, 1.39794001, 1.8920946 , 1.17609126,
        1.81291336, 1.95904139]])

# Boolean Filter


In [26]:
x=np.random.randint(0,100,(8,15))
print(x)


[[19 74 84 51 42 41  6 63 11 99 58 11 53 58 59]
 [99 26 36  5 59 24 12 41 95 15 14 94 45 28 28]
 [94 66 74 48 44 46  6 66 62 59 75 35 30 89 91]
 [34 15 20 58 29 16 47  4 99 66 18 91 15 22 86]
 [47 91 54 26 71  1 89 66 51 76 46 78  0 60 47]
 [54 20 52 87 57 56 23 61 84 63 98 37 36 43 11]
 [58 10 19 25  0 69 19 65 84 29 85 43  8 82 31]
 [54 69 86 33 15 36 12 91 24 99 72 32 23 72 94]]


In [27]:
x>50  # Just for display

array([[False,  True,  True,  True, False, False, False,  True, False,
         True,  True, False,  True,  True,  True],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False,  True, False, False, False],
       [ True,  True,  True, False, False, False, False,  True,  True,
         True,  True, False, False,  True,  True],
       [False, False, False,  True, False, False, False, False,  True,
         True, False,  True, False, False,  True],
       [False,  True,  True, False,  True, False,  True,  True,  True,
         True, False,  True, False,  True, False],
       [ True, False,  True,  True,  True,  True, False,  True,  True,
         True,  True, False, False, False, False],
       [ True, False, False, False, False,  True, False,  True,  True,
        False,  True, False, False,  True, False],
       [ True,  True,  True, False, False, False, False,  True, False,
         True,  True, False, False,  True,  True]])

In [28]:
x[x>50] #displays the values greater than 50

array([74, 84, 51, 63, 99, 58, 53, 58, 59, 99, 59, 95, 94, 94, 66, 74, 66,
       62, 59, 75, 89, 91, 58, 99, 66, 91, 86, 91, 54, 71, 89, 66, 51, 76,
       78, 60, 54, 52, 87, 57, 56, 61, 84, 63, 98, 58, 69, 65, 84, 85, 82,
       54, 69, 86, 91, 99, 72, 72, 94])

In [29]:
x[x<20]

array([19,  6, 11, 11,  5, 12, 15, 14,  6, 15, 16,  4, 18, 15,  1,  0, 11,
       10, 19,  0, 19,  8, 15, 12])

In [31]:
f1=x>20
f2=x<50
x[f1&f2]

array([42, 41, 26, 36, 24, 41, 45, 28, 28, 48, 44, 46, 35, 30, 34, 29, 47,
       22, 47, 26, 46, 47, 23, 37, 36, 43, 25, 29, 43, 31, 33, 36, 24, 32,
       23])