In [25]:
# For numpy

In [26]:
import numpy as np


In [27]:
x=0

# Num Mat

In [28]:
x=np.array([[1,2],[4,5]])
y=np.array([[6,7],[8,9]])
print(x)
print(y)

[[1 2]
 [4 5]]
[[6 7]
 [8 9]]


In [29]:
print(x*y)

[[ 6 14]
 [32 45]]


In [30]:
x+y

array([[ 7,  9],
       [12, 14]])

In [31]:
x/y

array([[0.16666667, 0.28571429],
       [0.5       , 0.55555556]])

In [32]:
z=x*y
print(z)

[[ 6 14]
 [32 45]]


In [33]:
np.dot(x,y)

array([[22, 25],
       [64, 73]])

In [34]:
np.cross(x,y)

array([-5, -4])

In [35]:
a=np.array([[1,2],[2,1]])
b=np.array([[3,3],[2,2]])


In [36]:
print(np.cross(a,b))
print(np.dot(a,b))

[-3  2]
[[7 7]
 [8 8]]


In [37]:
c=np.random.randint(0,100,(5,7))
print(c)

[[78 38 89 39 57 44 27]
 [37 55 20 65  6  5  7]
 [54 48 16 69 97 99  9]
 [64 65 41 52 37  0 31]
 [77 92 43 70 66  9 53]]


In [38]:
print(c.sum())

1659


In [39]:
print(c.sum(axis=0))  # 0 across column 
print(c.sum(axis=1))  # 1 across rows

[310 298 209 295 263 157 127]
[372 195 392 290 410]


In [40]:
print(c.mean())

47.4


In [41]:
print(c.mean(axis=0))
print(c.mean(axis=1))

[62.  59.6 41.8 59.  52.6 31.4 25.4]
[53.14285714 27.85714286 56.         41.42857143 58.57142857]


In [42]:
np.sin(c)

array([[ 0.51397846,  0.29636858,  0.86006941,  0.96379539,  0.43616476,
         0.01770193,  0.95637593],
       [-0.64353813, -0.99975517,  0.91294525,  0.82682868, -0.2794155 ,
        -0.95892427,  0.6569866 ],
       [-0.55878905, -0.76825466, -0.28790332, -0.11478481,  0.37960774,
        -0.99920683,  0.41211849],
       [ 0.92002604,  0.82682868, -0.15862267,  0.98662759, -0.64353813,
         0.        , -0.40403765],
       [ 0.99952016, -0.77946607, -0.83177474,  0.77389068, -0.02655115,
         0.41211849,  0.39592515]])

In [43]:
np.log10(c)

C:\Users\KumarCha05\AppData\Local\Temp\ipykernel_23872\2814158553.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(c)


array([[1.8920946 , 1.5797836 , 1.94939001, 1.59106461, 1.75587486,
        1.64345268, 1.43136376],
       [1.56820172, 1.74036269, 1.30103   , 1.81291336, 0.77815125,
        0.69897   , 0.84509804],
       [1.73239376, 1.68124124, 1.20411998, 1.83884909, 1.98677173,
        1.99563519, 0.95424251],
       [1.80617997, 1.81291336, 1.61278386, 1.71600334, 1.56820172,
              -inf, 1.49136169],
       [1.88649073, 1.96378783, 1.63346846, 1.84509804, 1.81954394,
        0.95424251, 1.72427587]])

# Boolean Filter


In [44]:
x=np.random.randint(0,100,(8,15))
print(x)


[[18  7 36 86 27 73 96 86 77 83 64 97 16 89 45]
 [78 33 73 50 50 17 56 93 89 10 50 80 75  9 11]
 [18 97 74 77 76 13 11  5 98 95 78 97 58 68 50]
 [78 10 87 55 98 10 53 62 99 50 65 33 43 51 25]
 [ 6 88 71  8 30 46 54 61 35  4 25 87 67 48 62]
 [24 90 60 23 56 60 30 54 50 56 86 33 24 34 47]
 [96  8 65 89 59 56 30 39 83 55 96 45 31  3  1]
 [84 40 50 48 59 52 30 72 67 67 52 88 73 63  8]]


In [45]:
x>50  # Just for display

array([[False, False, False,  True, False,  True,  True,  True,  True,
         True,  True,  True, False,  True, False],
       [ True, False,  True, False, False, False,  True,  True,  True,
        False, False,  True,  True, False, False],
       [False,  True,  True,  True,  True, False, False, False,  True,
         True,  True,  True,  True,  True, False],
       [ True, False,  True,  True,  True, False,  True,  True,  True,
        False,  True, False, False,  True, False],
       [False,  True,  True, False, False, False,  True,  True, False,
        False, False,  True,  True, False,  True],
       [False,  True,  True, False,  True,  True, False,  True, False,
         True,  True, False, False, False, False],
       [ True, False,  True,  True,  True,  True, False, False,  True,
         True,  True, False, False, False, False],
       [ True, False, False, False,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True, False]])

In [46]:
x[x>50] #displays the values greater than 50

array([86, 73, 96, 86, 77, 83, 64, 97, 89, 78, 73, 56, 93, 89, 80, 75, 97,
       74, 77, 76, 98, 95, 78, 97, 58, 68, 78, 87, 55, 98, 53, 62, 99, 65,
       51, 88, 71, 54, 61, 87, 67, 62, 90, 60, 56, 60, 54, 56, 86, 96, 65,
       89, 59, 56, 83, 55, 96, 84, 59, 52, 72, 67, 67, 52, 88, 73, 63])

In [47]:
x[x<20]

array([18,  7, 16, 17, 10,  9, 11, 18, 13, 11,  5, 10, 10,  6,  8,  4,  8,
        3,  1,  8])

In [48]:
f1=x>20
f2=x<50
x[f1&f2]

array([36, 27, 45, 33, 33, 43, 25, 30, 46, 35, 25, 48, 24, 23, 30, 33, 24,
       34, 47, 30, 39, 45, 31, 40, 48, 30])